---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: savantly-read-access
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "configmaps"
      - "services"
      - "deployments"
      - "replicasets"
      - "horizontalpodautoscalers"
      - "ingresses"
      - "namespaces"
      - "limitranges"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
      - "apps"
      - "autoscaling"
      - "networking.k8s.io"
    resources:
      - "deployments"
      - "ingresses"
      - "replicasets"
      - "horizontalpodautoscalers"
      - "statefulsets"
      - "daemonsets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - "pods"
      - "namespaces"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: savantly-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: savantly-read-access
subjects:
  - kind: User
    name: savantly
